((nil . ((bug-reference-url-format . "https://github.com/alex-hhh/time-zone-lookup-tests")
         (bug-reference-bug-regexp . "\\#\\(?2:[0-9]+\\)\\>")
         (indent-tabs-mode         . nil)
         (require-final-newline    . t)
         (show-trailing-whitespace . t)
         (ah-project-headline . "Time Zone Lookup Tests -- https://github.com/alex-hhh/time-zone-lookup-tests")
         (ah-project-license . gpl)))
 (yaml-mode . ((mode . goto-address)
               (mode . bug-reference)))
 (shell-script-mode . ((mode . goto-address)
                       (mode . bug-reference)))
 (log-view-mode . ((mode . goto-address)
                   (mode . bug-reference)))
 (log-edit-mode . ((mode . goto-address)
                   (mode . bug-reference)))
 (markdown-mode . ((mode . goto-address)
                   (mode . bug-reference)))
 (racket-mode . ((mode . goto-address)
                 (mode . bug-reference)
                 (ah-do-fixups . t)))
 (sql-mode . ((mode . goto-address)
              (mode . bug-reference)
              (sql-product . sqlite)
              (ah-do-fixups . t))))
